name: open_reactor_game
description: 'A multiplayer game inspired by "4 Player Reactor".'
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  husky: ^0.1.6
  lint_staged: ^0.4.2

flutter:
  uses-material-design: true

lint_staged:
  "lib/**.dart": dart format --fix
