name: open_reactor_game
description: 'A multiplayer game inspired by "4 Player Reactor".'
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flextras: ^1.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.8
  change_app_package_name: ^1.1.0
  custom_lint: ^0.6.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  husky: ^0.1.7
  json_serializable: ^6.7.1
  lint_staged: ^0.5.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

lint_staged:
  "lib/**.dart": dart format --fix
